# Google Cloud Build configuration for YAGO v8.0
# Automated CI/CD pipeline for Cloud Run deployment

steps:
  # Step 1: Build Backend Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/yago-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/yago-backend:latest'
      - '-f'
      - 'deployment/Dockerfile.backend'
      - '.'
    id: 'build-backend'

  # Step 2: Build Frontend Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/yago-frontend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/yago-frontend:latest'
      - '-f'
      - 'deployment/Dockerfile.frontend'
      - '.'
    id: 'build-frontend'

  # Step 3: Push Backend Image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/yago-backend:$COMMIT_SHA'
    id: 'push-backend'
    waitFor: ['build-backend']

  # Step 4: Push Frontend Image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/yago-frontend:$COMMIT_SHA'
    id: 'push-frontend'
    waitFor: ['build-frontend']

  # Step 5: Deploy Backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'yago-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/yago-backend:$COMMIT_SHA'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'ENVIRONMENT=production,LOG_LEVEL=info'
    id: 'deploy-backend'
    waitFor: ['push-backend']

  # Step 6: Deploy Frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'yago-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/yago-frontend:$COMMIT_SHA'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '5'
      - '--set-env-vars'
      - 'REACT_APP_API_URL=${_BACKEND_URL}'
    id: 'deploy-frontend'
    waitFor: ['push-frontend', 'deploy-backend']

# Timeout for entire build
timeout: '1200s'

# Images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/yago-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/yago-backend:latest'
  - 'gcr.io/$PROJECT_ID/yago-frontend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/yago-frontend:latest'

# Substitutions
substitutions:
  _BACKEND_URL: 'https://yago-backend-xxxx-ew.a.run.app'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
